// Generated by Grafana k6 Studio (1.9.0) on 2025-12-15T04:12:01.486Z

import { group, sleep, check } from "k6";
import http from "k6/http";
import execution from "k6/execution";

export const options = {
  stages: [
    { target: 20, duration: "1m" },
    { target: 20, duration: "3m30s" },
    { target: 0, duration: "1m" },
  ],
};

export default function () {
  let params;
  let resp;
  let match;
  let regex;
  let url;
  const correlation_vars = {};

  group("Default group", function () {
  params = {
      headers: {
        "Content-Type":"application/json"
      }
    }
    url = http.url`https://katalon-demo-cura.herokuapp.com/authenticate.php`;
    resp = http.request(
      "POST",
      url,
      JSON.parse(`{"username":"John Doe","password":"ThisIsNotAPassword"}`),
      params,
    );

    check(resp, { "status equals 200": (r) => r.status === 200 });
  });
  sleep(1);
}
